version: '3.2'

volumes:
  jenkins-home:

services:
  test:
    image: mijabr/test:latest
    restart: unless-stopped
    ports:
      - target: 80
        published: 5000
        protocol: tcp
        mode: host
